name: gold_calc_shagraf
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # برگشت به نسخه سازگار با گیت‌هاب
  intl: ^0.19.0
  http: ^1.2.0
  html: ^0.15.4
  home_widget: ^0.6.0
  tapsell_plus: ^2.3.2
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# تنظیمات آیکون برنامه
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/icon/icon.png"

# تنظیمات صفحه خوش‌آمدگویی (Splash Screen)
flutter_native_splash:
  color: "#1B5E20"
  image: "assets/icon/icon.png"
  android_12: 
    color: "#1B5E20"
    image: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn.ttf
